### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by mickeys000** [alfredosa/macos-window-manager#1]
Hi!
Is this for other people to be used as well?
If so, could you share screenshots and keyboard shortcuts for it?

**Comment by alfredosa** [comment]
Hey @mickeyserr yeah absolutely, I was planning on enhancing the README and publishing a crate soon as well so its easier to install. I will add Keycodes as config too so you don't have to use mine.

right now its Cmd + Ctrl + (left,right,up) Arrows. Will position your window based on the screen size.

I will add a video. 

It's as advanced of a Window Manager as I think it can be for the Mac Ecosystem

**Comment by mickeys000** [comment]
Great! Happy to wait for the crate and you finishing the housekeeping before giving it a go. Thank you very much. 😄
